-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R_A.SCORE
FROM REST_INFO I
JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
        FROM REST_REVIEW
        GROUP BY REST_ID) R_A
ON I.REST_ID = R_A.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY R_A.SCORE DESC, I.FAVORITES DESC
;